### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by ahmad-reza619** [KongkowITPekanbaru/masjid-network#14]
Because our project is open source, any help would be very appreciated, and so it would be great to make a CONTRIBUTING.md file to guide the new dev on the project!

### Task
- [ ] Explain what is masjid-network about
- [ ] Explain on the basic of how to contribute on open source
- [ ] Explain the procedure of cloning the project to actually running it in local
- [ ] Make the explanation into indonesian & english so people that couldn't talk in english or couldn't talk in indonesia understand the project

Also probably explain that were prioritising to use english as the base talking method. As english is an international level, so that people not just from indonesia could contribute and understand our project as well, But i'm not forcing it though. What do you think about this?

Pake bahasa indo aja atau inggris sebagai main method of communicating di repo ini?

**Comment by jufianto** [comment]
yes, i think we can use english as base talking of this repo or projects. but anyone prefrer use indoensian are welcome. 
sambil pelajari bahasa inggris wkwkw. 

for current situation I think we don't need manual how to contribute to this open source, because we still find the best method how to make this project better. but if someone here want to make contributing.md, you can make it, jut put PR and we will discuss in PR
